### ISSUE TITLE
don't work with redmine 3.2.0

### ISSUE THREAD

**Issue by msneet** [banica/redmine_hide_username#1]

**Comment by ineshezers** [comment]
Doesn't work with 3.1.4. eather.
When trying to install I get error:

```
bundle exec rake redmine:plugins:migrate RAILS_ENV=production --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
LoadError: cannot load such file -- /var/lib/redmine/plugins/hide_user_name_by_default/lib/user.rb
/usr/local/lib64/ruby/gems/2.0.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib64/ruby/gems/2.0.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib64/ruby/gems/2.0.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib64/ruby/gems/2.0.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/var/lib/redmine/plugins/redmine_hide_username/init.rb:1:in `<top (required)>'
/usr/local/lib64/ruby/gems/2.0.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib64/ruby/gems/2.0.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib64/ruby/gems/2.0.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib64/ruby/gems/2.0.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/var/lib/redmine/lib/redmine/plugin.rb:155:in `block in load'
/var/lib/redmine/lib/redmine/plugin.rb:146:in `each'
/var/lib/redmine/lib/redmine/plugin.rb:146:in `load'
[ ... ]
```

**Comment by banica** [comment]
Hi,

I'll check it why is not working. At this moment i am focused on a major update to this plugin and it's written mostly from scratch.

Thanks.

**Comment by arquio** [comment]
Doesn't work with 2.5.x.
When trying to install I get same error (its solve with a folder rename) and, alfter, I have problems with redmine_people plugin...
